# configuration parameters
api_keys:
  groq: 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
paths:
  data_raw: ../data/raw
  data_processed: ../data/processed
  images: ../images
  report: ../report
  addons: ../addons
  fonts: ../fonts
